// <auto-generated />
namespace Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ChapterLinkItemTextCanBeNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChapterLinkItemTextCanBeNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201801091751404_ChapterLinkItemTextCanBeNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
