//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWriterV2.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainRu() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebWriterV2.Localization.MainRu", typeof(MainRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все проекты портала.
        /// </summary>
        internal static string Admin_Books {
            get {
                return ResourceManager.GetString("Admin_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить опросник.
        /// </summary>
        internal static string Admin_Questionnaire_Add {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить вопрос.
        /// </summary>
        internal static string Admin_Questionnaire_AddQuestion {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить вариант ответа.
        /// </summary>
        internal static string Admin_Questionnaire_AddQuestionAnswer {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_AddQuestionAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможно выбрать несколько ответов.
        /// </summary>
        internal static string Admin_Questionnaire_AllowMultipleAnswers {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_AllowMultipleAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить вопрос №{0}?.
        /// </summary>
        internal static string Admin_Questionnaire_ConfirmRemovingQuestion {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_ConfirmRemovingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить ответ №{0} на вопрос №{1}?.
        /// </summary>
        internal static string Admin_Questionnaire_ConfirmRemovingQuestionAnswer {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_ConfirmRemovingQuestionAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить опросник с названием: &quot;{0}&quot;?.
        /// </summary>
        internal static string Admin_Questionnaire_ConfirmRemovingQuestionnaire {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_ConfirmRemovingQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название опросника.
        /// </summary>
        internal static string Admin_Questionnaire_DefaultName {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        internal static string Admin_Questionnaire_Edit {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступен свой вариант ответа.
        /// </summary>
        internal static string Admin_Questionnaire_EnableOtherAnswer {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_EnableOtherAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительный текст перед полем для своего ответа (не обязательно).
        /// </summary>
        internal static string Admin_Questionnaire_OtherLabel {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_OtherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос.
        /// </summary>
        internal static string Admin_Questionnaire_Question_DefaultName {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Question_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ.
        /// </summary>
        internal static string Admin_Questionnaire_QuestionAnswer_DefaultName {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_QuestionAnswer_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Admin_Questionnaire_Remove {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты опросов.
        /// </summary>
        internal static string Admin_Questionnaire_Result {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string Admin_Questionnaire_Save {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать авторам перед началом работы на сайте.
        /// </summary>
        internal static string Admin_Questionnaire_ShowBeforeFirstBook {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_ShowBeforeFirstBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опросники.
        /// </summary>
        internal static string Admin_Questionnaires {
            get {
                return ResourceManager.GetString("Admin_Questionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вас пригласили как соавтора для работы на произведением &quot;{0}&quot;.
        /// </summary>
        internal static string Email_MultiAuthorNotificationTitle {
            get {
                return ResourceManager.GetString("Email_MultiAuthorNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструкции по востановлению пароля на портал Naractivity.com.
        /// </summary>
        internal static string Email_RecoverPasswordTitle {
            get {
                return ResourceManager.GetString("Email_RecoverPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступна для связи.
        /// </summary>
        internal static string Landing_AvailableToLink {
            get {
                return ResourceManager.GetString("Landing_AvailableToLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать главу.
        /// </summary>
        internal static string Landing_FakeChapter {
            get {
                return ResourceManager.GetString("Landing_FakeChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальное состояние.
        /// </summary>
        internal static string Landing_InitState {
            get {
                return ResourceManager.GetString("Landing_InitState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить главу.
        /// </summary>
        internal static string Landing_RemoveChapter {
            get {
                return ResourceManager.GetString("Landing_RemoveChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разорвать связь.
        /// </summary>
        internal static string Landing_RemoveLink {
            get {
                return ResourceManager.GetString("Landing_RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст статьи.
        /// </summary>
        internal static string Reader_Article_DefaultDesc {
            get {
                return ResourceManager.GetString("Reader_Article_DefaultDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название статьи.
        /// </summary>
        internal static string Reader_Article_DefaultName {
            get {
                return ResourceManager.GetString("Reader_Article_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое описание статьи.
        /// </summary>
        internal static string Reader_Article_DefaultShortDesc {
            get {
                return ResourceManager.GetString("Reader_Article_DefaultShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статьи.
        /// </summary>
        internal static string Reader_Articles {
            get {
                return ResourceManager.GetString("Reader_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить статью.
        /// </summary>
        internal static string Reader_Articles_Add {
            get {
                return ResourceManager.GetString("Reader_Articles_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить статью &quot;{0}&quot;?.
        /// </summary>
        internal static string Reader_Articles_ConfirmRemovingArticle {
            get {
                return ResourceManager.GetString("Reader_Articles_ConfirmRemovingArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        internal static string Reader_Articles_Edit {
            get {
                return ResourceManager.GetString("Reader_Articles_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Развернуть.
        /// </summary>
        internal static string Reader_Articles_Expand {
            get {
                return ResourceManager.GetString("Reader_Articles_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название статьи.
        /// </summary>
        internal static string Reader_Articles_NamePlaceholder {
            get {
                return ResourceManager.GetString("Reader_Articles_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Публиковать.
        /// </summary>
        internal static string Reader_Articles_Publish {
            get {
                return ResourceManager.GetString("Reader_Articles_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Reader_Articles_Remove {
            get {
                return ResourceManager.GetString("Reader_Articles_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string Reader_Articles_Save {
            get {
                return ResourceManager.GetString("Reader_Articles_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите краткое описание статьи.
        /// </summary>
        internal static string Reader_Articles_ShortDescPlaceholder {
            get {
                return ResourceManager.GetString("Reader_Articles_ShortDescPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свернуть.
        /// </summary>
        internal static string Reader_Articles_UnExpand {
            get {
                return ResourceManager.GetString("Reader_Articles_UnExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить публикацию.
        /// </summary>
        internal static string Reader_Articles_UnPublish {
            get {
                return ResourceManager.GetString("Reader_Articles_UnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронная почта.
        /// </summary>
        internal static string Reader_Email {
            get {
                return ResourceManager.GetString("Reader_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        internal static string Reader_Exit {
            get {
                return ResourceManager.GetString("Reader_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забыли пароль?.
        /// </summary>
        internal static string Reader_ForgotPassword {
            get {
                return ResourceManager.GetString("Reader_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь.
        /// </summary>
        internal static string Reader_Help {
            get {
                return ResourceManager.GetString("Reader_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный логин или пароль.
        /// </summary>
        internal static string Reader_IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("Reader_IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        internal static string Reader_Login {
            get {
                return ResourceManager.GetString("Reader_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        internal static string Reader_Password {
            get {
                return ResourceManager.GetString("Reader_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить ответы.
        /// </summary>
        internal static string Reader_Questionnaire_Finish {
            get {
                return ResourceManager.GetString("Reader_Questionnaire_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться к работе.
        /// </summary>
        internal static string Reader_Questionnaire_ReturnToWork {
            get {
                return ResourceManager.GetString("Reader_Questionnaire_ReturnToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо за ваши ответы.
        /// </summary>
        internal static string Reader_Questionnaire_Thanks {
            get {
                return ResourceManager.GetString("Reader_Questionnaire_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Востановить пароль.
        /// </summary>
        internal static string Reader_RecoverPassword {
            get {
                return ResourceManager.GetString("Reader_RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        internal static string Reader_Registration {
            get {
                return ResourceManager.GetString("Reader_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        internal static string ReaderBooks_AllBooks {
            get {
                return ResourceManager.GetString("ReaderBooks_AllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОДОЛЖИТЬ ПУТЬ.
        /// </summary>
        internal static string ReaderBooks_ContinueTavel {
            get {
                return ResourceManager.GetString("ReaderBooks_ContinueTavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новые.
        /// </summary>
        internal static string ReaderBooks_NewBooks {
            get {
                return ResourceManager.GetString("ReaderBooks_NewBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочитанные.
        /// </summary>
        internal static string ReaderBooks_ReadBooks {
            get {
                return ResourceManager.GetString("ReaderBooks_ReadBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НАЧАТЬ ПУТЬ.
        /// </summary>
        internal static string ReaderBooks_StartTravel {
            get {
                return ResourceManager.GetString("ReaderBooks_StartTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НАЧАТЬ ЗАНОВО.
        /// </summary>
        internal static string ReaderBooks_TheBookIsReaded {
            get {
                return ResourceManager.GetString("ReaderBooks_TheBookIsReaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить главу &quot;{0}&quot;?.
        /// </summary>
        internal static string RemoveChapterConfirmation {
            get {
                return ResourceManager.GetString("RemoveChapterConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление главы &quot;{0}&quot; невозможно. Это приведет к появлению изолированных глав.
        /// </summary>
        internal static string RemoveChapterImpossibleAlert {
            get {
                return ResourceManager.GetString("RemoveChapterImpossibleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление связи невозможно. Это приведет к появлению изолированных глав.
        /// </summary>
        internal static string RemoveLinkImpossibleAlert {
            get {
                return ResourceManager.GetString("RemoveLinkImpossibleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тэги.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        internal static string Travel_Back {
            get {
                return ResourceManager.GetString("Travel_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        internal static string Travel_GetChosen {
            get {
                return ResourceManager.GetString("Travel_GetChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться в списку книг.
        /// </summary>
        internal static string Travel_GoToListOfBook {
            get {
                return ResourceManager.GetString("Travel_GoToListOfBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти к статистике.
        /// </summary>
        internal static string Travel_GoToStatistics {
            get {
                return ResourceManager.GetString("Travel_GoToStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующая глава.
        /// </summary>
        internal static string Travel_Next {
            get {
                return ResourceManager.GetString("Travel_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить тип.
        /// </summary>
        internal static string Writer_AddStateType {
            get {
                return ResourceManager.GetString("Writer_AddStateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да/Нет.
        /// </summary>
        internal static string Writer_BasicType_Boolean {
            get {
                return ResourceManager.GetString("Writer_BasicType_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число.
        /// </summary>
        internal static string Writer_BasicType_Number {
            get {
                return ResourceManager.GetString("Writer_BasicType_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст.
        /// </summary>
        internal static string Writer_BasicType_Text {
            get {
                return ResourceManager.GetString("Writer_BasicType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        internal static string Writer_BooleanFalse {
            get {
                return ResourceManager.GetString("Writer_BooleanFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        internal static string Writer_BooleanTrue {
            get {
                return ResourceManager.GetString("Writer_BooleanTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить изменения состояния?.
        /// </summary>
        internal static string Writer_ChangeRemoveConfirm {
            get {
                return ResourceManager.GetString("Writer_ChangeRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения состояния в случае выбора.
        /// </summary>
        internal static string Writer_ChangeTitle {
            get {
                return ResourceManager.GetString("Writer_ChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string Writer_ChangeType_Add {
            get {
                return ResourceManager.GetString("Writer_ChangeType_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отнять.
        /// </summary>
        internal static string Writer_ChangeType_Reduce {
            get {
                return ResourceManager.GetString("Writer_ChangeType_Reduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Writer_ChangeType_Remove {
            get {
                return ResourceManager.GetString("Writer_ChangeType_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задать.
        /// </summary>
        internal static string Writer_ChangeType_Set {
            get {
                return ResourceManager.GetString("Writer_ChangeType_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить соавтора с email &quot;{0}&quot;?.
        /// </summary>
        internal static string Writer_CoAuthorRemoveConfirm {
            get {
                return ResourceManager.GetString("Writer_CoAuthorRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        internal static string Writer_Confirm {
            get {
                return ResourceManager.GetString("Writer_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить произведение &quot;{0}&quot;?.
        /// </summary>
        internal static string Writer_ConfirmRemovingBook {
            get {
                return ResourceManager.GetString("Writer_ConfirmRemovingBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить пользователя &quot;{0}&quot;?.
        /// </summary>
        internal static string Writer_ConfirmRemovingUser {
            get {
                return ResourceManager.GetString("Writer_ConfirmRemovingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить имя или описание.
        /// </summary>
        internal static string Writer_EditNameOrDesc {
            get {
                return ResourceManager.GetString("Writer_EditNameOrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите описание книги.
        /// </summary>
        internal static string Writer_EnterBookDesc {
            get {
                return ResourceManager.GetString("Writer_EnterBookDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя книги.
        /// </summary>
        internal static string Writer_EnterBookName {
            get {
                return ResourceManager.GetString("Writer_EnterBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите тэг. Нажмите Enter.
        /// </summary>
        internal static string Writer_EnterTag {
            get {
                return ResourceManager.GetString("Writer_EnterTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все условия выбора заполнены.
        /// </summary>
        internal static string Writer_InvalidBranchLinkText {
            get {
                return ResourceManager.GetString("Writer_InvalidBranchLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите переменную и тип действия.
        /// </summary>
        internal static string Writer_InvalidChange {
            get {
                return ResourceManager.GetString("Writer_InvalidChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите переменную и тип сравнения.
        /// </summary>
        internal static string Writer_InvalidRequirement {
            get {
                return ResourceManager.GetString("Writer_InvalidRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проекты.
        /// </summary>
        internal static string Writer_Projects {
            get {
                return ResourceManager.GetString("Writer_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Публиковать.
        /// </summary>
        internal static string Writer_Publish {
            get {
                return ResourceManager.GetString("Writer_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Writer_RemoveBook {
            get {
                return ResourceManager.GetString("Writer_RemoveBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить условия видимости?.
        /// </summary>
        internal static string Writer_RequirementRemoveConfirm {
            get {
                return ResourceManager.GetString("Writer_RequirementRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условий для видимости данно выбора.
        /// </summary>
        internal static string Writer_RequirementTitle {
            get {
                return ResourceManager.GetString("Writer_RequirementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на =.
        /// </summary>
        internal static string Writer_RequirementType_Equals {
            get {
                return ResourceManager.GetString("Writer_RequirementType_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ∃.
        /// </summary>
        internal static string Writer_RequirementType_Exist {
            get {
                return ResourceManager.GetString("Writer_RequirementType_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;.
        /// </summary>
        internal static string Writer_RequirementType_Less {
            get {
                return ResourceManager.GetString("Writer_RequirementType_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ≤.
        /// </summary>
        internal static string Writer_RequirementType_LessOrEquals {
            get {
                return ResourceManager.GetString("Writer_RequirementType_LessOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;.
        /// </summary>
        internal static string Writer_RequirementType_More {
            get {
                return ResourceManager.GetString("Writer_RequirementType_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ≥.
        /// </summary>
        internal static string Writer_RequirementType_MoreOrEquals {
            get {
                return ResourceManager.GetString("Writer_RequirementType_MoreOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ≠.
        /// </summary>
        internal static string Writer_RequirementType_NotEquals {
            get {
                return ResourceManager.GetString("Writer_RequirementType_NotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ∄.
        /// </summary>
        internal static string Writer_RequirementType_NotExist {
            get {
                return ResourceManager.GetString("Writer_RequirementType_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string Writer_Save {
            get {
                return ResourceManager.GetString("Writer_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить и закрыть.
        /// </summary>
        internal static string Writer_SaveAndClose {
            get {
                return ResourceManager.GetString("Writer_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опубликована.
        /// </summary>
        internal static string Writer_StatePublished {
            get {
                return ResourceManager.GetString("Writer_StatePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить переменную &quot;{0}&quot; и все связанные с ней условия видимости, а так же изменения состояния?.
        /// </summary>
        internal static string Writer_StateTypeRemoveConfirm {
            get {
                return ResourceManager.GetString("Writer_StateTypeRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переменные доступные в книге.
        /// </summary>
        internal static string Writer_StateTypeTitle {
            get {
                return ResourceManager.GetString("Writer_StateTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Черновик.
        /// </summary>
        internal static string Writer_StateUnPublished {
            get {
                return ResourceManager.GetString("Writer_StateUnPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить публикацию.
        /// </summary>
        internal static string Writer_UnPublish {
            get {
                return ResourceManager.GetString("Writer_UnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работать на произведением.
        /// </summary>
        internal static string Writer_WorkOnProject {
            get {
                return ResourceManager.GetString("Writer_WorkOnProject", resourceCulture);
            }
        }
    }
}
