//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWriterV2.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainRu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebWriterV2.Localization.MainRu", typeof(MainRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все проекты портала.
        /// </summary>
        internal static string Admin_Books {
            get {
                return ResourceManager.GetString("Admin_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить опросник.
        /// </summary>
        internal static string Admin_Questionnaire_Add {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить вопрос.
        /// </summary>
        internal static string Admin_Questionnaire_AddQuestion {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить вариант ответа.
        /// </summary>
        internal static string Admin_Questionnaire_AddQuestionAnswer {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_AddQuestionAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможно выбрать несколько ответов.
        /// </summary>
        internal static string Admin_Questionnaire_AllowMultipleAnswers {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_AllowMultipleAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить вопрос №{0}?.
        /// </summary>
        internal static string Admin_Questionnaire_ConfirmRemovingQuestion {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_ConfirmRemovingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить ответ №{0} на вопрос №{1}?.
        /// </summary>
        internal static string Admin_Questionnaire_ConfirmRemovingQuestionAnswer {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_ConfirmRemovingQuestionAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить опросник с названием: &quot;{0}&quot;?.
        /// </summary>
        internal static string Admin_Questionnaire_ConfirmRemovingQuestionnaire {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_ConfirmRemovingQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название опросника.
        /// </summary>
        internal static string Admin_Questionnaire_DefaultName {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string Admin_Questionnaire_Edit {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступен свой вариант ответа.
        /// </summary>
        internal static string Admin_Questionnaire_EnableOtherAnswer {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_EnableOtherAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительный текст перед полем для своего ответа (не обязательно).
        /// </summary>
        internal static string Admin_Questionnaire_OtherLabel {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_OtherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос.
        /// </summary>
        internal static string Admin_Questionnaire_Question_DefaultName {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Question_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответ.
        /// </summary>
        internal static string Admin_Questionnaire_QuestionAnswer_DefaultName {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_QuestionAnswer_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Admin_Questionnaire_Remove {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты опросов.
        /// </summary>
        internal static string Admin_Questionnaire_Result {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Admin_Questionnaire_Save {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать авторам перед началом работы на сайте.
        /// </summary>
        internal static string Admin_Questionnaire_ShowBeforeFirstBook {
            get {
                return ResourceManager.GetString("Admin_Questionnaire_ShowBeforeFirstBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опросники.
        /// </summary>
        internal static string Admin_Questionnaires {
            get {
                return ResourceManager.GetString("Admin_Questionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вас пригласили как соавтора для работы на произведением &quot;{0}&quot;.
        /// </summary>
        internal static string Email_MultiAuthorNotificationTitle {
            get {
                return ResourceManager.GetString("Email_MultiAuthorNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкции по востановлению пароля на портал Naractivity.com.
        /// </summary>
        internal static string Email_RecoverPasswordTitle {
            get {
                return ResourceManager.GetString("Email_RecoverPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна для связи.
        /// </summary>
        internal static string Landing_AvailableToLink {
            get {
                return ResourceManager.GetString("Landing_AvailableToLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать главу.
        /// </summary>
        internal static string Landing_FakeChapter {
            get {
                return ResourceManager.GetString("Landing_FakeChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальное состояние.
        /// </summary>
        internal static string Landing_InitState {
            get {
                return ResourceManager.GetString("Landing_InitState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить главу.
        /// </summary>
        internal static string Landing_RemoveChapter {
            get {
                return ResourceManager.GetString("Landing_RemoveChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разорвать связь.
        /// </summary>
        internal static string Landing_RemoveLink {
            get {
                return ResourceManager.GetString("Landing_RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст статьи.
        /// </summary>
        internal static string Reader_Article_DefaultDesc {
            get {
                return ResourceManager.GetString("Reader_Article_DefaultDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название статьи.
        /// </summary>
        internal static string Reader_Article_DefaultName {
            get {
                return ResourceManager.GetString("Reader_Article_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое описание статьи.
        /// </summary>
        internal static string Reader_Article_DefaultShortDesc {
            get {
                return ResourceManager.GetString("Reader_Article_DefaultShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статьи.
        /// </summary>
        internal static string Reader_Articles {
            get {
                return ResourceManager.GetString("Reader_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить статью.
        /// </summary>
        internal static string Reader_Articles_Add {
            get {
                return ResourceManager.GetString("Reader_Articles_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить статью &quot;{0}&quot;?.
        /// </summary>
        internal static string Reader_Articles_ConfirmRemovingArticle {
            get {
                return ResourceManager.GetString("Reader_Articles_ConfirmRemovingArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string Reader_Articles_Edit {
            get {
                return ResourceManager.GetString("Reader_Articles_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть.
        /// </summary>
        internal static string Reader_Articles_Expand {
            get {
                return ResourceManager.GetString("Reader_Articles_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название статьи.
        /// </summary>
        internal static string Reader_Articles_NamePlaceholder {
            get {
                return ResourceManager.GetString("Reader_Articles_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публиковать.
        /// </summary>
        internal static string Reader_Articles_Publish {
            get {
                return ResourceManager.GetString("Reader_Articles_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Reader_Articles_Remove {
            get {
                return ResourceManager.GetString("Reader_Articles_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Reader_Articles_Save {
            get {
                return ResourceManager.GetString("Reader_Articles_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите краткое описание статьи.
        /// </summary>
        internal static string Reader_Articles_ShortDescPlaceholder {
            get {
                return ResourceManager.GetString("Reader_Articles_ShortDescPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свернуть.
        /// </summary>
        internal static string Reader_Articles_UnExpand {
            get {
                return ResourceManager.GetString("Reader_Articles_UnExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить публикацию.
        /// </summary>
        internal static string Reader_Articles_UnPublish {
            get {
                return ResourceManager.GetString("Reader_Articles_UnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        internal static string Reader_Email {
            get {
                return ResourceManager.GetString("Reader_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string Reader_Exit {
            get {
                return ResourceManager.GetString("Reader_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        internal static string Reader_ForgotPassword {
            get {
                return ResourceManager.GetString("Reader_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        internal static string Reader_Help {
            get {
                return ResourceManager.GetString("Reader_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный логин или пароль.
        /// </summary>
        internal static string Reader_IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("Reader_IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string Reader_Login {
            get {
                return ResourceManager.GetString("Reader_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Reader_Password {
            get {
                return ResourceManager.GetString("Reader_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить ответы.
        /// </summary>
        internal static string Reader_Questionnaire_Finish {
            get {
                return ResourceManager.GetString("Reader_Questionnaire_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к работе.
        /// </summary>
        internal static string Reader_Questionnaire_ReturnToWork {
            get {
                return ResourceManager.GetString("Reader_Questionnaire_ReturnToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за ваши ответы.
        /// </summary>
        internal static string Reader_Questionnaire_Thanks {
            get {
                return ResourceManager.GetString("Reader_Questionnaire_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Востановить пароль.
        /// </summary>
        internal static string Reader_RecoverPassword {
            get {
                return ResourceManager.GetString("Reader_RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string Reader_Registration {
            get {
                return ResourceManager.GetString("Reader_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string ReaderBooks_AllBooks {
            get {
                return ResourceManager.GetString("ReaderBooks_AllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить путь &gt;.
        /// </summary>
        internal static string ReaderBooks_ContinueTavel {
            get {
                return ResourceManager.GetString("ReaderBooks_ContinueTavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые.
        /// </summary>
        internal static string ReaderBooks_NewBooks {
            get {
                return ResourceManager.GetString("ReaderBooks_NewBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочитанные.
        /// </summary>
        internal static string ReaderBooks_ReadBooks {
            get {
                return ResourceManager.GetString("ReaderBooks_ReadBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать путь &gt;.
        /// </summary>
        internal static string ReaderBooks_StartTravel {
            get {
                return ResourceManager.GetString("ReaderBooks_StartTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочитана.
        /// </summary>
        internal static string ReaderBooks_TheBookIsReaded {
            get {
                return ResourceManager.GetString("ReaderBooks_TheBookIsReaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить главу &quot;{0}&quot;?.
        /// </summary>
        internal static string RemoveChapterConfirmation {
            get {
                return ResourceManager.GetString("RemoveChapterConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление главы &quot;{0}&quot; невозможно. Это приведет к появлению изолированных глав.
        /// </summary>
        internal static string RemoveChapterImpossibleAlert {
            get {
                return ResourceManager.GetString("RemoveChapterImpossibleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление связи невозможно. Это приведет к появлению изолированных глав.
        /// </summary>
        internal static string RemoveLinkImpossibleAlert {
            get {
                return ResourceManager.GetString("RemoveLinkImpossibleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тэги.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Travel_Back {
            get {
                return ResourceManager.GetString("Travel_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        internal static string Travel_GetChosen {
            get {
                return ResourceManager.GetString("Travel_GetChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться в списку книг.
        /// </summary>
        internal static string Travel_GoToListOfBook {
            get {
                return ResourceManager.GetString("Travel_GoToListOfBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к статистике.
        /// </summary>
        internal static string Travel_GoToStatistics {
            get {
                return ResourceManager.GetString("Travel_GoToStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующая глава.
        /// </summary>
        internal static string Travel_Next {
            get {
                return ResourceManager.GetString("Travel_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить тип.
        /// </summary>
        internal static string Writer_AddStateType {
            get {
                return ResourceManager.GetString("Writer_AddStateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да/Нет.
        /// </summary>
        internal static string Writer_BasicType_Boolean {
            get {
                return ResourceManager.GetString("Writer_BasicType_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число.
        /// </summary>
        internal static string Writer_BasicType_Number {
            get {
                return ResourceManager.GetString("Writer_BasicType_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        internal static string Writer_BasicType_Text {
            get {
                return ResourceManager.GetString("Writer_BasicType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string Writer_BooleanFalse {
            get {
                return ResourceManager.GetString("Writer_BooleanFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Writer_BooleanTrue {
            get {
                return ResourceManager.GetString("Writer_BooleanTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить изменения состояния?.
        /// </summary>
        internal static string Writer_ChangeRemoveConfirm {
            get {
                return ResourceManager.GetString("Writer_ChangeRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения состояния в случае выбора.
        /// </summary>
        internal static string Writer_ChangeTitle {
            get {
                return ResourceManager.GetString("Writer_ChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Writer_ChangeType_Add {
            get {
                return ResourceManager.GetString("Writer_ChangeType_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отнять.
        /// </summary>
        internal static string Writer_ChangeType_Reduce {
            get {
                return ResourceManager.GetString("Writer_ChangeType_Reduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Writer_ChangeType_Remove {
            get {
                return ResourceManager.GetString("Writer_ChangeType_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать.
        /// </summary>
        internal static string Writer_ChangeType_Set {
            get {
                return ResourceManager.GetString("Writer_ChangeType_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить соавтора с email &quot;{0}&quot;?.
        /// </summary>
        internal static string Writer_CoAuthorRemoveConfirm {
            get {
                return ResourceManager.GetString("Writer_CoAuthorRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        internal static string Writer_Confirm {
            get {
                return ResourceManager.GetString("Writer_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить произведение &quot;{0}&quot;?.
        /// </summary>
        internal static string Writer_ConfirmRemovingBook {
            get {
                return ResourceManager.GetString("Writer_ConfirmRemovingBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить пользователя &quot;{0}&quot;?.
        /// </summary>
        internal static string Writer_ConfirmRemovingUser {
            get {
                return ResourceManager.GetString("Writer_ConfirmRemovingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить имя или описание.
        /// </summary>
        internal static string Writer_EditNameOrDesc {
            get {
                return ResourceManager.GetString("Writer_EditNameOrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите описание книги.
        /// </summary>
        internal static string Writer_EnterBookDesc {
            get {
                return ResourceManager.GetString("Writer_EnterBookDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя книги.
        /// </summary>
        internal static string Writer_EnterBookName {
            get {
                return ResourceManager.GetString("Writer_EnterBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите тэг. Нажмите Enter.
        /// </summary>
        internal static string Writer_EnterTag {
            get {
                return ResourceManager.GetString("Writer_EnterTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не все условия выбора заполнены.
        /// </summary>
        internal static string Writer_InvalidBranchLinkText {
            get {
                return ResourceManager.GetString("Writer_InvalidBranchLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите переменную и тип действия.
        /// </summary>
        internal static string Writer_InvalidChange {
            get {
                return ResourceManager.GetString("Writer_InvalidChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите переменную и тип сравнения.
        /// </summary>
        internal static string Writer_InvalidRequirement {
            get {
                return ResourceManager.GetString("Writer_InvalidRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекты.
        /// </summary>
        internal static string Writer_Projects {
            get {
                return ResourceManager.GetString("Writer_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публиковать.
        /// </summary>
        internal static string Writer_Publish {
            get {
                return ResourceManager.GetString("Writer_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить книгу.
        /// </summary>
        internal static string Writer_RemoveBook {
            get {
                return ResourceManager.GetString("Writer_RemoveBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить условия видимости?.
        /// </summary>
        internal static string Writer_RequirementRemoveConfirm {
            get {
                return ResourceManager.GetString("Writer_RequirementRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условий для видимости данно выбора.
        /// </summary>
        internal static string Writer_RequirementTitle {
            get {
                return ResourceManager.GetString("Writer_RequirementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string Writer_RequirementType_Equals {
            get {
                return ResourceManager.GetString("Writer_RequirementType_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∃.
        /// </summary>
        internal static string Writer_RequirementType_Exist {
            get {
                return ResourceManager.GetString("Writer_RequirementType_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string Writer_RequirementType_Less {
            get {
                return ResourceManager.GetString("Writer_RequirementType_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≤.
        /// </summary>
        internal static string Writer_RequirementType_LessOrEquals {
            get {
                return ResourceManager.GetString("Writer_RequirementType_LessOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string Writer_RequirementType_More {
            get {
                return ResourceManager.GetString("Writer_RequirementType_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≥.
        /// </summary>
        internal static string Writer_RequirementType_MoreOrEquals {
            get {
                return ResourceManager.GetString("Writer_RequirementType_MoreOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≠.
        /// </summary>
        internal static string Writer_RequirementType_NotEquals {
            get {
                return ResourceManager.GetString("Writer_RequirementType_NotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∄.
        /// </summary>
        internal static string Writer_RequirementType_NotExist {
            get {
                return ResourceManager.GetString("Writer_RequirementType_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Writer_Save {
            get {
                return ResourceManager.GetString("Writer_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить и закрыть.
        /// </summary>
        internal static string Writer_SaveAndClose {
            get {
                return ResourceManager.GetString("Writer_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликована.
        /// </summary>
        internal static string Writer_StatePublished {
            get {
                return ResourceManager.GetString("Writer_StatePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить переменную &quot;{0}&quot; и все связанные с ней условия видимости, а так же изменения состояния?.
        /// </summary>
        internal static string Writer_StateTypeRemoveConfirm {
            get {
                return ResourceManager.GetString("Writer_StateTypeRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переменные доступные в книге.
        /// </summary>
        internal static string Writer_StateTypeTitle {
            get {
                return ResourceManager.GetString("Writer_StateTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черновик.
        /// </summary>
        internal static string Writer_StateUnPublished {
            get {
                return ResourceManager.GetString("Writer_StateUnPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить публикацию.
        /// </summary>
        internal static string Writer_UnPublish {
            get {
                return ResourceManager.GetString("Writer_UnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работать на произведением.
        /// </summary>
        internal static string Writer_WorkOnProject {
            get {
                return ResourceManager.GetString("Writer_WorkOnProject", resourceCulture);
            }
        }
    }
}
